version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: memory-tester-db
    environment:
      POSTGRES_DB: memory_tester
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - memory-tester-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: memory-tester-server
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: memory_tester
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - memory-tester-network
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://192.168.0.185:3001
    container_name: memory-tester-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - memory-tester-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  memory-tester-network:
    driver: bridge
